namespace TD2_WinUI3
{
	//[default_interface]
	runtimeclass NullToVisibilityConverter : [default] Microsoft.UI.Xaml.Data.IValueConverter
	{
		NullToVisibilityConverter();

		[noexcept]
		Microsoft.UI.Xaml.Visibility NullValue;

		[noexcept]
		Microsoft.UI.Xaml.Visibility NonNullValue;
	}
}
